tasks:
  - name: Install Mamba
    init: |
      curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
      sudo mv bin/micromamba /usr/local/bin/micromamba
      echo 'export MAMBA_ROOT_PREFIX=~/micromamba' >> ~/.bashrc
      echo 'eval "$(micromamba shell hook --shell=bash)"' >> ~/.bashrc
      source ~/.bashrc
      micromamba create -n base -y -c conda-forge mamba
      micromamba activate base
    command: |
        mamba create -n ONT25 -y bioconda::busco
        mamba activate ONT25
